### ISSUE TITLE
Coco dataset?

### ISSUE THREAD

**Issue by FlorinAndrei** [shubham0204/Bounding_Box_Regression_TF#2]
Nice project, it's similar to things I'm working on.

Any thoughts on doing bounding boxes in TF/Keras (same as this project) but using the Coco dataset?

http://cocodataset.org/

**Comment by shubham0204** [comment]
The COCO dataset contains multiple boxes for a single image. Meaning, each image can have annotations for multiple objects present in it. Bounding Box Regression is for detecting a single object in an image.

**Comment by shubham0204** [comment]
Bounding Box Regression is relatively less powerful than other Object Detection algorithms. For COCO, I would insist on YOLO or FasterRCNN.
